namespace Spectrometer.Models;

public partial class HardwareStatus : ObservableObject
{
    // ------------------------------------------------------------------------------------------------
    // Public Fields
    //   Backing fields automatically generated by CommunityToolkit.Mvvm
    //   These are accessible in all View Models and XAML - see DashboardViewModel.cs for implementation
    // ------------------------------------------------------------------------------------------------

    [ObservableProperty]
    private bool _isLoading = true;

    // ------------------------------------------------------------------------------------------------
    // Motherboard

    [ObservableProperty]
    private string _mbName = string.Empty;

    // ------------------------------------------------------------------------------------------------
    // CPU

    [ObservableProperty]
    private string _cpuImagePath = string.Empty;

    [ObservableProperty]
    private string _cpuName = string.Empty;

    [ObservableProperty]
    private float _cpuTemp;

    [ObservableProperty]
    private float _cpuUsage;

    [ObservableProperty]
    private float _cpuPower;

    [ObservableProperty]
    private float _cpuPowerMax;

    // ------------------------------------------------------------------------------------------------
    // GPU

    [ObservableProperty]
    private string _gpuImagePath = string.Empty;

    [ObservableProperty]
    private string _gpuName = string.Empty;

    [ObservableProperty]
    private float _gpuTemp;

    [ObservableProperty]
    private float _gpuUsage;

    [ObservableProperty]
    private float _gpuPower;

    [ObservableProperty]
    private float _gpuPowerMax;

    // ------------------------------------------------------------------------------------------------
    // Memory

    [ObservableProperty]
    private string _memoryUsageDetails = string.Empty;

    [ObservableProperty]
    private double _memoryUsageGb;

    [ObservableProperty]
    private double _memoryTotalGb;
}
