name: Publish Application

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish Spectrometer.csproj --configuration Release --output ./publish --no-restore /p:PublishProfile=PackagedApplication

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Spectrometer
        path: ./publish
